version: "3.0"
services:
  database:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 3ayYMPwCd2maT3yuPGS6dnY7XC4CRnvb
      MYSQL_DATABASE: customer
      MYSQL_USER: customer
      MYSQL_PASSWORD: 3ayYMPwCd2maT3yuPGS6dnY7XC4CRnvb
    ports:
      - "127.0.0.1:3306:3306"

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 127.0.0.1:8000:8080
